services:
  llm-app:
    container_name: app
    image: llms-engineering/app:0.0.1
    ports:
      -  8501:8501
    networks:
      - local_network
    volumes:
      - .env.prod:/app/.env
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.11.0
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./data/qdrant_storage:/app/qdrant/storage
    networks:
      - local_network
  ollama:
    container_name: ollama
    image: ollama/ollama:0.3.6
    ports:
      - 11434:11434
    volumes:
      - ~/.ollama:/root/.ollama
    networks:
      - local_network
      
networks:
  local_network:
    driver: bridge
